### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by houshuang** [uts-cic/tap#102]
I just installed the latest version, and tried running the examples in GraphiQL. Athanor is down, clean text and make visible work, but for the others I get NullPointerException, for example for annotations:

```bash
[info] play.api.Play - Application started (Dev)
[info] a.e.s.Slf4jLogger - Slf4jLogger started
[info] factorie-nlp-api - Completed in 8085 ms
[info] t.p.Annotating - Factorie started successfully [4 tokens]
java.lang.NullPointerException
	at cc.factorie.app.nlp.Token.parseChildren(Token.scala:118)
	at tap.pipelines.Annotating.$anonfun$tapSentences$4(Annotating.scala:93)
	at scala.collection.immutable.List.map(List.scala:283)
	at tap.pipelines.Annotating.$anonfun$tapSentences$3(Annotating.scala:92)
	at scala.collection.immutable.List.map(List.scala:283)
	at tap.pipelines.Annotating.$anonfun$tapSentences$2(Annotating.scala:91)
	at akka.stream.impl.fusing.Map$$anon$7.onPush(Ops.scala:47)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:499)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:401)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:571)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:457)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:546)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:728)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:743)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:653)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
	at akka.actor.ActorCell.invoke(ActorCell.scala:496)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by andrewresearch** [comment]
Make sure you have enough memory allocated to the JVM to be able to load the models and ensure the models are on your classpath.

A new version that uses different libraries for accessing Factorie will be merged in in the next day or so. You may like to wait until then, and try again.

**Comment by andrewresearch** [comment]
Try cloning this version, and let me know if it works for you.

**Comment by houshuang** [comment]
Thanks, this is much better. Athanor still down, some other giving errors, but a number of them work well.

TokeniseWithNer
```bash
java.lang.NoClassDefFoundError: Could not initialize class io.nlytx.nlp.annotators.NerTagger$
	at io.nlytx.nlp.api.AnnotatorPipelines$.$anonfun$nerTagger$2(AnnotatorPipelines.scala:43)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:653)
	at scala.util.Success.$anonfun$map$1(Try.scala:251)
	at scala.util.Success.map(Try.scala:209)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:287)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:140)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

I also had an out-of-memory, that seems to have resolved itself
```bash
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.regex.Matcher.<init>(Matcher.java:225)
	at java.util.regex.Pattern.matcher(Pattern.java:1093)
	at scala.util.matching.Regex$MatchIterator.<init>(Regex.scala:788)
	at scala.util.matching.Regex.findAllIn(Regex.scala:392)
	at cc.factorie.app.strings.RegexSegmenter$$anon$1.<init>(StringSegmenter.scala:32)
	at cc.factorie.app.strings.RegexSegmenter.apply(StringSegmenter.scala:31)
	at cc.factorie.nlp.lexicon.TriePhraseLexicon.$plus$eq(TriePhraseLexicon.scala:21)
	at cc.factorie.nlp.lexicon.TriePhraseLexicon.$anonfun$$plus$plus$eq$1(TriePhraseLexicon.scala:28)
	at cc.factorie.nlp.lexicon.TriePhraseLexicon.$anonfun$$plus$plus$eq$1$adapted(TriePhraseLexicon.scala:28)
	at cc.factorie.nlp.lexicon.TriePhraseLexicon$$Lambda$8697/361018116.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
	at cc.factorie.nlp.lexicon.TriePhraseLexicon.$plus$plus$eq(TriePhraseLexicon.scala:28)
	at cc.factorie.nlp.lexicon.TriePhraseLexicon.$plus$plus$eq(TriePhraseLexicon.scala:17)
	at cc.factorie.nlp.lexicon.MutableLexicon.$plus$plus$eq(MutableLexicon.scala:18)
	at cc.factorie.nlp.lexicon.MutableLexicon.$plus$plus$eq$(MutableLexicon.scala:18)
	at cc.factorie.nlp.lexicon.TriePhraseLexicon.$plus$plus$eq(TriePhraseLexicon.scala:17)
	at cc.factorie.nlp.lexicon.ProvidedLexicon.$init$(ProvidedLexicon.scala:11)
	at cc.factorie.nlp.lexicon.ProvidedTriePhraseLexicon.<init>(ProvidedTriePhraseLexicon.scala:7)
	at cc.factorie.nlp.lexicon.wikipedia.Person.<init>(WikipediaLexicon.scala:79)
	at cc.factorie.nlp.lexicon.StaticLexicons$wikipedia$Person$.<init>(StaticLexicons.scala:106)
	at cc.factorie.nlp.lexicon.StaticLexicons$wikipedia$.Person$lzycompute$1(StaticLexicons.scala:106)
	at cc.factorie.nlp.lexicon.StaticLexicons$wikipedia$.Person(StaticLexicons.scala:106)
	at cc.factorie.nlp.ner.StaticLexiconFeatures.<init>(StaticLexiconFeatures.scala:50)
	at io.nlytx.nlp.annotators.EnglishLexiconFeatures$.<init>(EnglishLexiconFeatures.scala:9)
	at io.nlytx.nlp.annotators.EnglishLexiconFeatures$.<clinit>(EnglishLexiconFeatures.scala)
	at io.nlytx.nlp.annotators.NerTagger$.<init>(NerTagger.scala:8)
	at io.nlytx.nlp.annotators.NerTagger$.<clinit>(NerTagger.scala)
	at io.nlytx.nlp.api.AnnotatorPipelines$.$anonfun$nerTagger$2(AnnotatorPipelines.scala:43)
	at io.nlytx.nlp.api.AnnotatorPipelines$$$Lambda$8742/82128054.apply(Unknown Source)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:653)
```

I run on a Mac, OSX 10.12.16, 16 GB RAM, command `_JAVA_OPTIONS="-Xmx2048M -Xss1M" sbt run`

**Comment by andrewresearch** [comment]
You'll need to give the JVM at least 4G maybe 6G to successfully load the NER models. Also, if you're getting the noClassDef error, run sbt clean before sbt compile. Otherwise, should be running without errors.
Athanor (test server) is temporarily down. Will be attending to that soon. You should at least see the error message in TAP now instead of the NPE.

**Comment by houshuang** [comment]
Can confirm that all services (except Athanor-ones) work with higher memory
limit and sbt clean!

You might want to update instructions in the docs to specify higher memory
limit

```

   1.

   Ensure the JVM has enough memory to run the application.

   export _JAVA_OPTIONS="-Xmx2048M -Xss1M"


​```

**Comment by andrewresearch** [comment]
Thanks for your persistence, and for your suggestion.
Would you like to make the change to the docs and send PR? Otherwise, please create an issue for this and I'll get someone onto it :-)

**Comment by andrewresearch** [comment]
A final update that should fix another bug I introduced when fixing the original athanor issue. This is version 3.0.9 and will be the beginning of a release candidate for 3.1

**Comment by andrewresearch** [comment]
I've updated the docs.
